#!/usr/bin/python

### Import custom directives:
import codeblock
from subprocess import Popen
from subprocess import PIPE

### Now run rst2html:
rst2html = Popen(['which', 'rst2html'], stdout=PIPE).communicate()[0].rstrip()
execfile(rst2html)
